; Generated by snesdev-util 0.01 alpha

; MetaSpriteFrameSets
	; MetaSpriteFrame_player
	MetaSpriteFrame_player_standRight = 0
	MetaSpriteFrame_player_walkRight = 1
	MetaSpriteFrame_player_turnRight = 2
	MetaSpriteFrame_player_jumpRight = 3
	MetaSpriteFrame_player_fallRight = 4
	MetaSpriteFrame_player_pushButtonRight = 5
	MetaSpriteFrame_player_zappedRight = 6
	MetaSpriteFrame_player_standLeft = 7
	MetaSpriteFrame_player_walkLeft = 8
	MetaSpriteFrame_player_turnLeft = 9
	MetaSpriteFrame_player_jumpLeft = 10
	MetaSpriteFrame_player_fallLeft = 11
	MetaSpriteFrame_player_pushButtonLeft = 12
	MetaSpriteFrame_player_zappedLeft = 13


.global MetaSpriteFrameTable

.global MetaSpriteFrameTable_elevator
.global MetaSprite_player
	.global MetaSprite_player_standRight
	.global MetaSprite_player_walkRight
	.global MetaSprite_player_turnRight
	.global MetaSprite_player_jumpRight
	.global MetaSprite_player_fallRight
	.global MetaSprite_player_pushButtonRight
	.global MetaSprite_player_zappedRight
	.global MetaSprite_player_standLeft
	.global MetaSprite_player_walkLeft
	.global MetaSprite_player_turnLeft
	.global MetaSprite_player_jumpLeft
	.global MetaSprite_player_fallLeft
	.global MetaSprite_player_pushButtonLeft
	.global MetaSprite_player_zappedLeft

